### ISSUE TITLE
I'm porting this extension to Rust and wordcut-engine

### ISSUE THREAD

**Issue by veer66** [zdk/pg-search-thai#3]
I use wordcut-engine instead of libthai. https://github.com/veer66/chamkho-pg

**Comment by zdk** [comment]
@veer66 Awesome!! 
You and me must be starving for some Thai food during coding for sure, LMAO 😆  just see code examples given in readme.
Btw, https://github.com/veer66/chamkho-pg is looking good 🥇 
will check it out 😍
